### ISSUE TITLE
PDF (bylaws) not displayed in the browser

### ISSUE THREAD

**Issue by jangondol** [pyconsk/spy.python.sk#8]
The link to https://spy.pycon.sk/static/download/SPy_stanovy.pdf has a weird behavior. When downloading the file via wget, the PDF is transferred correctly (the hash is identical to the file in the repository). When displaying the link in Chrome or Safari, only a blank page is shown. Tested this on both Mac (Chrome 63, Safari 11) and Linux (Chrome 63).

Everything works just fine in Firefox (Quantum 57, Linux).

Can you reproduce this? (I am seeing other PDFs in the "problematic" browsers just fine.) Is the server sending the correct headings (Content-Type etc.)? If anyone would like to troubleshoot this, feel free!

**Comment by dn0** [comment]
Confirmed. It is cause by the `Content-Security-Policy` header.
It is related to our web server configuration. I've created an internal issue for this.

**Comment by dn0** [comment]
Fixed
